language: cpp

  
compiler:
  - g++

script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-dev
  - cd Hola
  - mkdir build
  - cd holaWorld-master
  - cmake cmake -H. -B../build
   - cd ../build
  - make
  
